name: Build and Deploy React App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Detect output folder (Vite=dist, CRA=build) and prepare SPA + .nojekyll
      - name: Prepare output
        shell: bash
        run: |
          if [ -d "dist" ]; then OUT=dist; elif [ -d "build" ]; then OUT=build; else echo "No dist or build folder found"; exit 1; fi
          echo "BUILD_DIR=$OUT" >> $GITHUB_ENV
          cp "$OUT/index.html" "$OUT/404.html" || true
          touch "$OUT/.nojekyll"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_DIR }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
